Add task-21-02-15 files
nike4192/cpp_urfu_2 pull request #6
Opened 2021-02-24 10:11 UTC by nike4192

2021-02-25 16:58 UTC, Toxin65 requested changes
У меня к вам много вопросов.
Вы неплохо потрудились. И показали некоторые подходы. Но сильно больше требований ТЗ и не всегда уместно. Разберём.

2021-02-25 16:58 UTC, Toxin65 commented on task-21-02-15/Vector2.h
> +	double x, y;
Оговорка. Я два раза одну и ту же ошибку указывать не буду.
Снова инкапсуляция.

2021-02-25 16:58 UTC, Toxin65 commented on task-21-02-15/Vector2.cpp
> +double Vector2::cross(Vector2& v)
Псевдоскалярное, ага... Я тоже заметил ошибку в ТЗ уже потом.
Нехватает const-ов.

2021-02-25 16:58 UTC, Toxin65 commented on task-21-02-15/Vector2.cpp
> +	return Vector2(*this) /= this->length();
Не надо this->length();, просто length();
Вы же внутри экземпляра.

2021-02-25 16:58 UTC, Toxin65 commented on task-21-02-15/Vector2.cpp
> +	return pow(x * x + y * y, 1 / 2);
sqrt же

2021-02-25 16:58 UTC, Toxin65 commented on task-21-02-15/Vector2.cpp
> +Vector2& Vector2::operator+=(Vector2& v)
ох, const-ы, const-ы...

2021-02-25 16:58 UTC, Toxin65 commented on task-21-02-15/PhysicalValue.h
> +class PhysicalValue
Это overkill, не надо тут шаблонов...
И даже, если их использовать, я не в восторге от вашего подхода...

2021-02-25 16:58 UTC, Toxin65 commented on task-21-02-15/PhysicalValue.cpp
> +PhysicalValue<T>::PhysicalValue(T _value) : value(_value) {}
Шаблоны, обычно, только в заголовочных описываются. Что-то я сомневаюсь, что тут всё будет гладко по некоторым причинам.

2021-02-25 16:58 UTC, Toxin65 commented on task-21-02-15/ChessPiece.h
> +enum CHESS_PIECE { KING, QUEEN, ROOK, BISHOP, KNIGHT, PAWN };
Это всё overkill, достаточно по заданию было описать класс для
>1.4.	Позиции фигуры на шахматной доске

Не более, неважно какой фигуры.
Я понимаю ваше рвение, вы неплохо потрудились, но сделали сильно больше, чем требовалось по заданию.

2021-03-03 07:27 UTC, Toxin65 requested changes
Некоторые старые комменты не исправлены. Новые исправить.
Если коммент написан в одном месте, надо исправлять подобные замечания в других местах тоже. Ошибки типичные.

2021-03-03 07:27 UTC, Toxin65 commented on task-21-02-15/Amperage.h
> +	double getValue();
const
Обговаривали же этот момент.

2021-03-03 07:27 UTC, Toxin65 commented on task-21-02-15/Amperage.cpp
> +}
Желательно в конце файлов оставлять пустые строки.

2021-03-03 07:27 UTC, Toxin65 commented on task-21-02-15/Complex.h
> +	Complex operator+(const Complex& c);
Богу const-ов нужно больше const-ов!

2021-03-03 07:27 UTC, Toxin65 commented on task-21-02-15/Vector4.h
> +	Vector4 operator-(double s);
Эрм, а что, вектор можно алгебраически складывать со скаляром?

2021-03-03 07:27 UTC, Toxin65 commented on task-21-02-15/ChessBoard.h
> +у каждой ячейки можеть быть максимум одна фигура (ассоциативность)
Это на какой вопрос ответ?
Обозначьте, пожалуйста, все, чтобы я не гадал.

2021-03-03 13:40 UTC, nike4192 commented on task-21-02-15/Complex.h
> +	Complex operator+(const Complex& c);
Я убрал const, потому что результат операции возвращает констовый элемент и при дальнейших операциях пишет,
что не определен оператор const A с A

2021-06-15 15:34 UTC, Toxin65 approved these changes
В целом хорошо.

2022-03-22 21:33 UTC, merged